<?php

namespace AppBundle\Repository;

use AppBundle\Entity\User;

/**
 * MessageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MessageRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByUser(User $user){
        $qb = $this->createQueryBuilder('m');
        $qb->andWhere('m.user = :user')
            ->setParameter('user', $user)
            ->addOrderBy('m.date','desc');
        return $qb->getQuery()->getResult();
    }
}
