<?php

namespace AppBundle\Repository;

/**
 * ReceptRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReceptRepository extends \Doctrine\ORM\EntityRepository
{
}
