<?php

namespace AppBundle\Repository;

use AppBundle\Entity\User;

/**
 * MeetingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MeetingRepository extends \Doctrine\ORM\EntityRepository
{
    public function findOldForUser(User $user){
        $qb = $this->createQueryBuilder('m');
        $qb->andWhere('m.user = :user')
            ->andWhere('m.startDate < :now');
        $qb->setParameter('user', $user)
            ->setParameter('now', new \DateTime());
        return $qb->getQuery()->getResult();
    }

    public function findNewForUser(User $user){
        $qb = $this->createQueryBuilder('m');
        $qb->andWhere('m.user = :user')
            ->andWhere('m.startDate >= :now');
        $qb->setParameter('user', $user)
            ->setParameter('now', new \DateTime());
        return $qb->getQuery()->getResult();
    }
}
